promptToReturnFromSubprocess: false
notARepository: quit

gui:
  showCommandLog: true
  commandLogSize: 5
  border: rounded
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  mainBranches: [master, main, staging, production]

  commitPrefixes:
    crm-frontend:
      pattern: "(\\w+-\\w+).*"
      replace: '[$1] '
    crm-backend:
      pattern: "(\\w+-\\w+).*"
      replace: '[$1] '
    frontend:
      pattern: "(\\w+-\\w+).*"
      replace: '[$1] '
    hrd:
      pattern: "(\\w+-\\w+).*"
      replace: '[$1] '
    packages:
      pattern: "(\\w+-\\w+).*"
      replace: '[$1] '
