promptToReturnFromSubprocess: false
git:
  autofetch: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  commitPrefixes:
    crm-frontend:
      pattern: "\\w+-(\\w+).*"
      replace: '[$1] '
    crm-backend:
      pattern: "\\w+-(\\w+).*"
      replace: '[$1] '
    frontend:
      pattern: "\\w+-(\\w+).*"
      replace: '[$1] '
    hrd:
      pattern: "\\w+-(\\w+).*"
      replace: '[$1] '
notARepository: quit
