#!/bin/bash

bspc rule -r "*"


### --- Autostart --- ###

xrdb ~/.Xresources &

fehbg &
~/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &


### --- Settings --- ###

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 e

# bsp-layout set monocle 3
# bsp-layout set tall 5
# bsp-layout set tall 7
# bsp-layout set monocle 8
# bsp-layout set monocle 9

bspc config automatic_scheme alternate
bspc config initial_polarity first_child
bspc config split_ratio 0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config single_monocle   true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config border_width 2

bspc config normal_border_color "#282A36"
# bspc config active_border_color "#44475A"
# bspc config focused_border_color "#6272A4"
# bspc config presel_feedback_color "#6272A4"

# bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config top_padding 27
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 10

bspc config external_rules_command ~/.config/bspwm/rules

~/.config/bspwm/cleanfullscreen &

autostart &
